apiVersion: v1
kind: Service
metadata:
  name: lakefront-ray-head
  namespace: default
spec:
  # LoadBalancer type for external access
  # Change to ClusterIP if you only need internal access
  type: LoadBalancer
  
  selector:
    # These labels are automatically added by KubeRay to head node pods
    ray.io/cluster: lakefront-ray-cluster
    ray.io/node-type: head
  
  ports:
    # Ray dashboard
    - name: dashboard
      port: 8265
      targetPort: 8265
      protocol: TCP
    
    # Ray client connection
    - name: client
      port: 10001
      targetPort: 10001
      protocol: TCP
    
    # Ray GCS server (optional, for advanced use cases)
    - name: gcs-server
      port: 6379
      targetPort: 6379
      protocol: TCP
